# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59605cc8854c0517b2a545f9b8e2e156708df1ca8748f79c608a5d7a0e7fd1524250481eca8c6ddb39f788fec581849dd65d06582a8433a78615766eb6174562

test:
  secret_key_base: b36f483e8acbebde41eec6a3bef625465263a8a3c323f43275c7f6c71ceb53bbf5667bd43cca4b073b2a98f00ed35b87f9c04801aa21a8350a628dbe96214cd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
